name: 'Conventional commits verification'

on: [create, push, pull_request, pull_request_review, pull_request_target]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: enforce-commit-msg-style
        uses: webiny/action-conventional-commits@v1.1.0